# Generated by Django 5.1.4 on 2025-04-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='name',
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
