# Generated by Django 5.2 on 2025-04-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_parent_alt_phone_parent_country_parent_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='profession',
            new_name='parents_profession',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='previous_employers',
        ),
    ]
