# Generated by Django 5.2 on 2025-04-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_profession_parent_parents_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='child_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
