# Generated by Django 5.2 on 2025-04-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_daycare_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='plain_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
