# Generated by Django 5.2 on 2025-04-17 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_staff_plain_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_age', models.IntegerField(help_text='Minimum age in years')),
                ('max_age', models.IntegerField(help_text='Maximum age in years')),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.daycare')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.group'),
        ),
    ]
