# Generated by Django 4.2.7 on 2025-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_group_child_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.CharField(blank=True, choices=[('Infant', 'Infant'), ('Toddlers', 'Toddlers'), ('Preschool', 'Preschool'), ('School Aged', 'School Aged')], max_length=50, null=True),
        ),
    ]
